#!/usr/bin/env python3
"""Build the Vietnamese PDF font that jsPDF embeds, from the OFL source in humiley-procurement.

Run:  python3 tools/make_vn_font.py

Why this exists rather than a checked-in blob nobody can reproduce: the subset is a derived
artefact, and when the character set changes (a new symbol on a document) the next person needs to
be able to rebuild it rather than guess how it was made.

Why a .js file and not a .ttf: app.py's CONTENT_TYPES has no .ttf entry, so a raw font is served as
application/octet-stream; and jsPDF's addFileToVFS wants base64 in the first place. Shipping it as
JavaScript also lets the service worker treat it like any other vendored script.
"""
import base64
import io
import os

from fontTools.subset import Options, Subsetter
from fontTools.ttLib import TTFont

SRC = "humiley-procurement/lib/pdf/fonts"
OUT = "static/vendor/tk-font-vn.js"
# The OFL requires the licence to travel with any redistributed copy of the font, and a subset is
# still a copy. It sits beside the generated asset; keep it there.
LICENCE = "static/vendor/tk-font-vn.OFL.txt"

# ASCII, Latin-1 supplement, Latin Extended-A, the two Vietnamese blocks, and the handful of
# typographic marks the documents actually use — including ₫, which _pdfSafe used to rewrite as
# "VND " precisely because it could not be drawn.
CODEPOINTS = set(range(0x20, 0x7F)) | set(range(0xA0, 0x180)) \
    | set(range(0x1A0, 0x1B1)) | set(range(0x1EA0, 0x1EFA)) \
    | {ord(c) for c in "₫€–—‘’“”•…°×"}


def build(style, filename):
    # recalcTimestamp=False: otherwise fontTools stamps head.modified with the build time and two
    # runs of this script produce two different files, so "rebuild it rather than guess" would mean
    # a spurious diff every time.
    f = TTFont(os.path.join(SRC, filename), recalcTimestamp=False)
    have = set()
    for t in f["cmap"].tables:
        have |= set(t.cmap.keys())
    want = sorted(CODEPOINTS & have)
    o = Options()
    o.layout_features = []          # jsPDF ignores OpenType layout entirely...
    o.hinting = False               # ...and does not use hinting either
    o.notdef_outline = True
    # layout_features=[] empties the feature lists but still ships the tables. jsPDF's TTF parser
    # only ever reads cmap/glyf/loca/hmtx/head/hhea/maxp/post, so these are pure payload.
    o.drop_tables += ["DSIG", "GDEF", "GPOS", "GSUB"]
    s = Subsetter(options=o)
    s.populate(unicodes=want)
    s.subset(f)
    buf = io.BytesIO()
    f.save(buf)
    raw = buf.getvalue()
    print("  %-8s %6d glyphs  %7d bytes ttf  %7d bytes base64"
          % (style, len(want), len(raw), len(base64.b64encode(raw))))
    return base64.b64encode(raw).decode("ascii")


def main():
    print("Subsetting Be Vietnam Pro (SIL Open Font License 1.1):")
    reg = build("regular", "BeVietnamPro-Regular.ttf")
    bold = build("bold", "BeVietnamPro-Bold.ttf")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(
            "/* Be Vietnam Pro, subset for PDF generation.\n"
            " * Copyright 2021 The Be Vietnam Pro Project Authors\n"
            " * (https://github.com/bettergui/BeVietnamPro)\n"
            " * Licensed under the SIL Open Font License 1.1 — https://scripts.sil.org/OFL\n"
            " *\n"
            " * GENERATED by tools/make_vn_font.py — do not edit by hand; rebuild instead.\n"
            " * Without this, jsPDF draws Vietnamese text with the standard-14 WinAnsi fonts and\n"
            " * produces mojibake. */\n"
            "window.TK_VN_FONT = {\n  regular: \"%s\",\n  bold: \"%s\"\n};\n" % (reg, bold))
    print("wrote %s (%d bytes)" % (OUT, os.path.getsize(OUT)))
    if not os.path.exists(LICENCE):
        raise SystemExit("%s is missing — the OFL must ship with the font." % LICENCE)


if __name__ == "__main__":
    main()
